### ISSUE TITLE
Browser Example

### ISSUE THREAD

**Issue by incowia-danilo** [alonrbar/easy-template-x#1]
Browser example for the README.md file: 

## Browser Example
import {TemplateHandler} from 'easy-template-x';
import save from 'save-file';
import JSZip from 'jszip';
import JSZipUtils from 'jszip-utils';

loadFile = (url,callback) => {
    JSZipUtils.getBinaryContent(url,callback);
}

myEasyTemplate = () => {
    this.loadFile("myTemplate.docx",function(error,content){
        if (error) { throw error };

        const data = {
            posts: [
                { author: 'Easy', text: 'Very important\ntext here!' },
                { author: 'Easy', text: 'Forgot to mention that...' }
            ]
        };

        const handler = new TemplateHandler();
        handler.process(content, data).then(doc => 
        {
            save.sync(doc, "easy-output.docx");        
        });
    })
}

**Comment by alonrbar** [comment]
Hi, 
Thanks for the offer!
I understand the need for having a full browser example. But ended up adding another example since I prefer having an example that doesn't require the user to download an additional library. It's visible now in the readme file.
