### ISSUE TITLE
Errors in types when compiling

### ISSUE THREAD

**Issue by R0BB3RT** [alonrbar/easy-template-x#10]
Hi,

I'm having some trouble compiling. I'm getting a bunch of errors in the types files.
https://hastebin.com/ajebujisaz.cs

I added the library to an Angular 8.0 project.

**Comment by alonrbar** [comment]
Hi,

Thanks for letting me know!
I'm actually using babel in my projects so I don't encounter this error. I'll fix this in the next couple of days and add some tests to make sure it stays fixed.
For the sake of completeness, can you specify what version of the library and what typescript version are you using?

**Comment by R0BB3RT** [comment]
Great! I'm using library version 0.8.0. And using typescript version 3.5.3.

Thanks in advance!

**Comment by alonrbar** [comment]
Fixed in 0.8.1.
You'll also need to add `"types" : ["node"]` in your `tsconfig.app.json` file (see [here](https://stackoverflow.com/questions/51256473/angular-cannot-find-name-buffer)).
