### ISSUE TITLE
Is it possible to add images in existing document using ReactJS ?

### ISSUE THREAD

**Issue by seeprogramming** [alonrbar/easy-template-x#101]
I have tried to implement images logic , I was able to replace text but not able to do with {%image}. Is there any example or snippets available for ReactJS ?

**Comment by alonrbar** [comment]
Image insertion is documented in the readme. It's here: https://github.com/alonrbar/easy-template-x?tab=readme-ov-file#image-plugin. We do not use a leading % sign. Please see the details there.
