### ISSUE TITLE
Question: How could we render an array of string

### ISSUE THREAD

**Issue by datcv** [alonrbar/easy-template-x#104]
I have an array as below:
```
{
    "Arr": ["item 1", "item 2", "Item 3"]
}
```

Currently could not render this into docx template unless each item in the array is an object.

**Comment by alonrbar** [comment]
That's right. In order to render an array each element needs to be an object, so you can reference the field you want to render in the template. We could have support some made up keyword like "value" or something but preferred to avoid it and be explicit.
