### ISSUE TITLE
Question: Preview Output before generating

### ISSUE THREAD

**Issue by AllekP** [alonrbar/easy-template-x#111]
Hi, 

I would like to find out, if it would be possible to preview the output before you generate the document? Also once the data is populated would it be possible to edit it?

**Comment by alonrbar** [comment]
You don't need a special mechanism for this. Just clone the template in memory and generate the document as many times as you need. If you are running on the server and reading the template to a Buffer (using with `fs.readFile` for instance) then you can clone the template with [Buffer.from](https://nodejs.org/api/buffer.html#static-method-bufferfrombuffer). If you are in the browser and using a Blob then you should be just fine to reuse the same Blob again as Blobs are supposed to be immutable.
