### ISSUE TITLE
Swap JSZip for a more performant zip solution

### ISSUE THREAD

**Issue by whekin** [alonrbar/easy-template-x#114]
I recently moved one of my projects to Bun, and for some reason JSZip is super slow (5-10x slower). As an experiment I swapped JSZip to PizZip and not only it worked great in Bun, it quite improved document generation speed in node as well.
I think I can contribute for this one

**Comment by alonrbar** [comment]
Hi,
Thank you for your suggestion. Few points come to mind in that regard:
1. First of all it is interesting to understand the actual numbers here. Can you add some benchmarking data about this?
2. PizZip id actually a fork of an older version of JsZip. It is also _a lot_ less popular: https://npmtrends.com/jszip-vs-pizzip
3. I use the library in a project for generating a document with dozens of pages on the client side and it takes less than a second, so speed was never an issue for me. I wonder, in what practical use cases did you find the generation speed limiting?

**Comment by whekin** [comment]
@alonrbar Thanks for quick answer

1. I just did some benchmarking with Bun, and it didn't show any issues with JSZip/Zip class in easy-template-x. JSZip was even faster. Nevertheless, when I switched from a fork to original easy-template-x, the Zip.export method started to take forever again (2-3 seconds instead of 10-20ms). Node runs both with similar performance with no issues
2. It's a fork, though it's maintained and used by Docxtemplater
3. In my case total generation goes over 10 seconds because of the issue

I need to do some more investigation, but somehow a switch to a different zip library in a fork helped to resolve the issue

**Comment by alonrbar** [comment]
I see. Interesting. Let me know when you find something.

**Comment by alonrbar** [comment]
Hi @whekin, any news worth sharing?

**Comment by whekin** [comment]
Hey @alonrbar! I faced some other issues with Bun. It seems not quite stable yet, so I switched back to node

**Comment by whekin** [comment]
So, I think this issue could be closed for now

**Comment by alonrbar** [comment]
Cool. Closing and if you find something interesting in the future feel free to reopen.

**Comment by whekin** [comment]
@alonrbar Just saw an opened [issue](https://github.com/oven-sh/bun/issues/12397) on jszip performing extremely slow in the Bun's repo. Though I think it's anyways on Bun to make it working optimal
