### ISSUE TITLE
"XML maximum depth reached (max depth: 20)." error in new TemplateHandler().process()

### ISSUE THREAD

**Issue by truviztech** [alonrbar/easy-template-x#115]
If an image is inserted inside a shape, the process method fails with an error "XML maximum depth reached (max depth: 20).". Most of the templates are built by placing an image inside a shape. 

For example,

If the template contains the image directly placed like below, there is no error

![image](https://github.com/alonrbar/easy-template-x/assets/166736927/583660ae-dcaf-4a3a-801b-8108c12f8ff0)

But if it is placed inside a shape like below, it throws an error

![image](https://github.com/alonrbar/easy-template-x/assets/166736927/ca1663d8-4853-4f1b-8001-16607785b2f7)

How do I handle this issue?

**Comment by alonrbar** [comment]
You can set the XML max depth value to whatever you want. Please take a look at the readme, here: https://github.com/alonrbar/easy-template-x?tab=readme-ov-file#template-handler-options.
