### ISSUE TITLE
Loop to create tables?

### ISSUE THREAD

**Issue by abs** [alonrbar/easy-template-x#116]
Hello!

I'm trying to find a way to loop over a list of objects, where each one results in its own table.

Doesn't look like it's possible right now - what would it take to add this capability?

**Comment by alonrbar** [comment]
It's actually one of the first things this package was capable of doing. Consider this data:

```
{
  students: [
    {
       name: "Michael",
       grades: [
         {
            subject: "Math",
            grade: 90
         }
       ]
    }
  ]
}
```

The you'd have two loops, one start before the table and ends after it (students loop), and the other is inside the table (grades loop). The result will be a separate table per student with multiple rows equivalent to the number of grades each student has.
