### ISSUE TITLE
Export images array drawn from canvas gives the error `[object Object]`

### ISSUE THREAD

**Issue by khanhduy1407** [alonrbar/easy-template-x#119]
I add placeholder in Word:

![image](https://github.com/user-attachments/assets/43184903-655c-4ae6-914a-1b1281d1b4a4)

And my code (React):

```ts
let blobList: any = [];

const createImageFromCanvas = async () => {
  const cefWidth = 3371;
  const cefHeight = 2420;

  const canvas = canvasRefs.current;
  if (!canvas) return;

  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const image = new Image();
  image.crossOrigin = "Anonymous";
  image.src = temData.image;

  image.onload = () => {
    // ...draw text...
  }

  await new Promise<void>((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        console.log(URL.createObjectURL(blob));
        blobList.push({
          _type: "image",
          source: URL.createObjectURL(blob),
          format: MimeType.Png,
          width: 500,
          height: 359,
        });
        resolve();
      }
    });
  });
}

const getTemplate = async (): Promise<Blob> => {
  if (theTemplate) return theTemplate;
  const request = await fetch("/files/template_test.docx");
  const defaultTemplate = await request.blob();
  return defaultTemplate;
};

const saveFile = (filename: string, blob: Blob) => {
  // get downloadable url from the blob
  const blobUrl = URL.createObjectURL(blob);

  // create temp link element
  let link: HTMLAnchorElement | null = document.createElement("a");
  link.download = filename;
  link.href = blobUrl;

  // use the link to invoke a download
  document.body.appendChild(link);
  link.click();

  // remove the link
  setTimeout(() => {
    if (link) {
      link.remove();
      URL.revokeObjectURL(blobUrl);
      link = null;
    }
  }, 0);
};

const download = async (e: any) => {
  e.preventDefault();

  console.log("Getting the template...");
  const templateFile = await getTemplate();

  await createImageFromCanvas()

  const jsonData: any = {
    blobList,
    // more data...
  };

  console.log("Parsing data...");
  // const jsonData = getJsonData();
  const data = JSON.parse(JSON.stringify(jsonData));
  console.log(data);

  console.log("Creating document...");
  const handler = new TemplateHandler();
  const docx = await handler.process(templateFile, data);

  console.log("Done!");
  saveFile("output.docx", docx);
};
```

Log in devtool:

![image](https://github.com/user-attachments/assets/950f6fd3-04de-4ee9-852d-ef6c7a48061f)

The results I got:

![image](https://github.com/user-attachments/assets/ed2611a4-fbe8-4253-8bf0-e3a1ba77b7a9)

**Comment by alonrbar** [comment]
First of all, the `source` attribute accepts a blob, not a URL. So instead of this:
```
{
  _type: "image",
  source: URL.createObjectURL(blob),
  format: MimeType.Png,
  width: 500,
  height: 359,
}
```
Do this:
```
{
  _type: "image",
  source: blob,
  format: MimeType.Png,
  width: 500,
  height: 359,
}
```

Second, you can't render a list directly, you need to use a loop for that. Please see: https://github.com/alonrbar/easy-template-x?tab=readme-ov-file#loop-plugin

**Comment by khanhduy1407** [comment]
I tried updating the above code according to your instructions:

```diff
await new Promise<void>((resolve) => {
  canvas.toBlob((blob) => {
    if (blob) {
      console.log(URL.createObjectURL(blob));
      blobList.push({
        _type: "image",
-       source: URL.createObjectURL(blob),
+       source: blob,
        format: MimeType.Png,
        width: 500,
        height: 359,
      });
      resolve();
    }
  });
});

// ...

const jsonData: any = {
-  blobList,
+  blobList: blobList[0], // test for one object
  // more data...
};
```

But I still get the error: Binary type 'Object' is not supported

![image](https://github.com/user-attachments/assets/91fc5d04-5c31-4f11-afb4-878922b9ab75)

**Comment by alonrbar** [comment]
Not sure what your bug is but here's a code sandbox that works: https://codesandbox.io/p/sandbox/easy-template-x-canvas-demo-dg78mh
I trust that you'll get it from here.
Good luck :)

**Comment by khanhduy1407** [comment]
Thank you very much, I did it successfully, it seems like this in my code is the cause:

```ts
const data = JSON.parse(JSON.stringify(jsonData)); // remove this line
```

removed this line and it worked fine

**Comment by khanhduy1407** [comment]
For this list of images, how do I write a placeholder in Word?

**Comment by alonrbar** [comment]
Did you read the loop plugin instructions I linked before?

**Comment by khanhduy1407** [comment]
Yes, I have read it, I add placeholder `{#blobList}{/}` in Word, log in devtools

![image](https://github.com/user-attachments/assets/11fbb550-b5f4-41fc-a405-02510e6ca8fb)

The result I get is no image at all, just a blank sheet of paper

What I did in the comments above is only for 1 image

**Comment by khanhduy1407** [comment]
If I write the placeholder `{#blobList}{1}{2}{/}`, only 2 images (1 and 2) will appear in the array in the image above.

**Comment by alonrbar** [comment]
Your template should look like this:

`{#blobList}{my image}{/}`

And the data like this:
```
{
  blobList: [
   {
     "my image": {
       _type: "image",
       source: blob,
       format: MimeType.Png,
       width: 500,
       height: 359,
     }
   },
   {
     "my image": {
       _type: "image",
       source: blob,
       format: MimeType.Png,
       width: 500,
       height: 359,
     }
   }
  ]
}
```

Meaning, the data is an array of objects where each object has a "my image" field (you can name it however you like of course) and the value of this field is the object that represents the image, with _type and all. This is similar to the way the "Beers" list is a list of objects where each has "Brand" and "Price" fields.

**Comment by khanhduy1407** [comment]
I got it, it worked great, thanks for your support ❤️.
