### ISSUE TITLE
Insert base64 image - Error: Binary type 'Object' is not supported.

### ISSUE THREAD

**Issue by Hobby-Student** [alonrbar/easy-template-x#122]
Hi @alonrbar,

thank you for your efforts! I test your software with a self-hosted n8n. For testing purposes I'm using your `template.docx` with the "Beer brand list".

If I use the following JSON for a "Link" things do work:
![image](https://github.com/user-attachments/assets/2c1a64ef-772c-404d-8e7b-a689cb42d815)

If I try to insert an image from a base64 string with
`Buffer.from($('When clicking ‘Test workflow’').item.json.Bild64, 'base64')`
I get the following:
![image](https://github.com/user-attachments/assets/6e92d4b4-81bb-42ce-8b62-e77e419d34ed)

in code:
`{"_type":"image","format":"image/jpeg","source":{"type":"Buffer","data":[117,...,217]},"width":200,"height":200}`

Whenever I execute this, I get `Error: Binary type 'Object' is not supported.`

Could you please tell me, what I'm doing wrong?

**Comment by alonrbar** [comment]
Take a look at some of the existing and closed issues, there several that resemble your case. Checkout #40, #60, #98, #101, #119 and perhaps others. And in any case remember, the debugger is your friend 😉
