### ISSUE TITLE
Adding plugins from an angular project

### ISSUE THREAD

**Issue by thegnuu** [alonrbar/easy-template-x#19]
Hi @alonrbar,

Me again ;) This has not a high priority for me personally, but it might become an issue for other users.

I am currently implementing new plugins. Adding the plugins directly in my fork works great, but if I try to do this from "outside" in my example from my angular application the following error occurs:

`TypeError: Class constructor TemplatePlugin cannot be invoked without 'new'`

I had no time to dig into this issue further, I have to prepare a release of the new version of our app and will stick to implement it in my fork. 

I will update this issue as soon as I found something helpful.

**Comment by alonrbar** [comment]
Hello :)
I'll look into it shortly.
If you think your plugins may be useful to others it may be a good idea to add a "community plugins" section in the readme file and point to your published library.

**Comment by thegnuu** [comment]
We can totally do this... I am currently working on a plugin to render deltas from quill (https://quilljs.com/) but at the moment I don't need a lot of features quill offers. You are as well able to implement custom contents to quill, I need to find a way to provide how custom stuff should be rendered...

I will have a look at this and let you know the repo as soon as I am ready :)

**Comment by alonrbar** [comment]
Great 👍

I created an angular project and imported easy-template-x, created a custom plugin and it all works. 
Maybe it's because of the new typing files. I've uploaded the latest version to npm (0.8.2) checkout if it works for you.

**Comment by thegnuu** [comment]
Allright, sounds good. I need to finish a few other things today - I will try the newest version on monday and let you know if it works!

**Comment by alonrbar** [comment]
Hi,
Closing this issue now. If it happens again feel free to let me know and re-open.

**Comment by thegnuu** [comment]
Hi @alonrbar 

I am sorry, we are working at some client projects at the moment and I am really busy.
I will let you know if there are still issues as soon as I got time to check this out.

Thank you!

**Comment by alonrbar** [comment]
No problem, take your time 👍
