### ISSUE TITLE
Headers are ignored

### ISSUE THREAD

**Issue by Neko-Mashiro** [alonrbar/easy-template-x#25]
Is there any way to replace variables in the header of a word file, when using a custom template on the demo page it did not replace any of the header text.

**Comment by alonrbar** [comment]
Hi Neko,

You are right, currently headers are kept untouched.

I deliberately avoided from adding this feature because I found it to be confusing if one opens a loop tag (say {#my-loop}) in the header and closes it outside of the header, for instance in the footer. What should the library then do? Should it repeat the entire page? Should it throw an error? Should it ignore these tags altogether?

Just to add some complexity to it, internally headers are saved in different xml files from the main document and may be split across up to 4 different files (you can read about it [here](http://officeopenxml.com/WPSectionHeaderReference.php)).

Since at the time I didn't need it in any of my projects I decided to just leave the headers untouched.

P.S. If you don't mind sharing, what is the use case you need this feature for?

**Comment by Neko-Mashiro** [comment]
I see, 

Currently we need it to replace simple variables in the header (duh) which can be done with docxtemplater however we don't like that you have to pay for features like images so this one is preferable. 

As for how it would function since it is already separated in different xml files and it is quite separated in word would it not make sense to ignore anything in the main page while searching through headers?

**Comment by alonrbar** [comment]
You are right, it does make sense to implement only simple variable replacement but I want to make sure all corners are covered and that loops are somehow handles gracefully (gracefully can be throwing an informative error) before adding it to the library and I'm not sure I can address this in the short future. 

**However** version 0.10.0 had just come out and includes a new [Extensions API](https://github.com/alonrbar/easy-template-x#extensions) and the `Docx.rawZipFile` property. You can easily write an extension that does exactly what you want. It would basically looks like this:

```typescript
class HeaderExtension extends TemplateExtension {

    public async execute(data, context) {
        const headerPaths = [ 'word/header1.xml', 'word/header2.xml', 'word/header3.xml' ];
        for (const headerPath of headerPaths) {
            const headerText = await context.docx.rawZipFile.getFile(headerPath).getContentText();
            const headerXml = this.utilities.xmlParser.parse(headerText);
            await this.utilities.compiler.compile(headerXml, data, context);
            const processedHeaderText = this.utilities.xmlParser.serializer(headerXml);
            context.docx.rawZipFile.setFile(headerPath, processedHeaderText);
       }
    }
}
```

**Comment by Neko-Mashiro** [comment]
So I finally got around to reading headers but I cannot seem to figure out how to hook into the parseTags function as it seems to never activate there. Some help would be appreciated.

**Comment by alonrbar** [comment]
I don't really understand why do you want to hook into the `parseTags` method...?
Do ask how to use this extension? It's explained [in the readme](https://github.com/alonrbar/easy-template-x#extensions), and in any case here is a short snippet:

```typescript
const handler = new TemplateHandler({
    extensions: {
        afterCompilation: [
            new HeaderExtension()
        ]
    }
});
```

If this does not answer your question, please give more details or attach a code sample to clarify what you mean.

**Comment by Neko-Mashiro** [comment]
I have an app where users can import a template to be stored on a server so it can be exported at a later date populated with relevant data, The way they do this is by having a tag editor built into the app and I need to read the tags at import so I can link them to the document and ensure they are always present. 
So what I need to do is read all the tags at import including headers and then later export them to the template. 
I have figured out how to replace them on export (handler.process) but not on import (handler.parseTags) unless there is a different way of getting the tags.

**Comment by alonrbar** [comment]
That's a good use case to consider when adding the feature to the library in the future. Thank you for that.

To get the tags now you can add this line inside your custom extension:

```typescript
const tags = this.utilities.compiler.parseTags(headerXml);
```

And export it outside somehow. One possible way to export data from the extension is to store it on the extension object. It would look something like this:

```typescript

// extension code

class HeaderExtension extends TemplateExtension {

    public headerTags: Tag[];

    public async execute(data, context) {
        const headerPaths = [ 'word/header1.xml', 'word/header2.xml', 'word/header3.xml' ];
        for (const headerPath of headerPaths) {
            const headerText = await context.docx.rawZipFile.getFile(headerPath).getContentText();
            const headerXml = this.utilities.xmlParser.parse(headerText);
            this.headerTags = this.utilities.compiler.parseTags(headerXml);
       }
    }
}

// use extension to get the tags

const headerExtension = new HeaderExtension();
const handler = new TemplateHandler({
    extensions: {
        afterCompilation: [
            headerExtension 
        ]
    }
});

await handler.process(...);
const headerTags = headerExtension.headerTags;
```

Another approach would be the raise an event from the extension and listen to it from the outside. These solutions are somewhat hacky but will achieve what you need.

**Comment by Neko-Mashiro** [comment]
So I was trying out this way of getting the header tags and for some reason `await context.docx.rawZipFile.getFile(headerPath).getContentText()` started throwing 

> TypeError: Cannot read property 'async' of undefined

and it is also affecting the other header extension method shown previously. Do you know if this is project specific or if its a possible bug with the package.

My code is:
```
import { TemplateExtension, TemplateContext, ScopeData, Tag } from "easy-template-x";

export class HeaderExtension extends TemplateExtension {
  public async execute(data: ScopeData, context: TemplateContext): Promise<void> {
    const headerPaths = ['word/header1.xml', 'word/header2.xml', 'word/header3.xml'];
    for (const headerPath of headerPaths) {
      const headerText = await context.docx.rawZipFile.getFile(headerPath).getContentText();
      const headerXml = this.utilities.xmlParser.parse(headerText);
      await this.utilities.compiler.compile(headerXml, data, context);
      const processedHeaderText = this.utilities.xmlParser.serialize(headerXml);
      context.docx.rawZipFile.setFile(headerPath, processedHeaderText);
    }
  }
}

export class HeaderParseExtension extends TemplateExtension {

  public headerTags: Tag[];

  public async execute(data: ScopeData, context: TemplateContext): Promise<void> {
    const headerPaths = ['word/header1.xml', 'word/header2.xml', 'word/header3.xml'];
    for (const headerPath of headerPaths) {
      const headerText = await context.docx.rawZipFile.getFile(headerPath).getContentText();
      const headerXml = this.utilities.xmlParser.parse(headerText);
      this.headerTags = this.utilities.compiler.parseTags(headerXml);
    }
  }
}
```
```
const handler = new TemplateHandler({
  delimiters: new Delimiters({
    containerTagClose: "$"
  }),
  extensions: {
    beforeCompilation: [
      new HeaderExtension()
    ]
  }
});
const docx = await handler.process(file, data);
```
In the case that it is specific to my project in which case I can revert to the latest commit however as I have a lot of work done already I would prefer not to throw it away if i don't have to.
Appreciate your help.

**Comment by alonrbar** [comment]
Basically that means that the header file you're trying to open does not exist.

No all documents have headers and the one that does, does not always have 3 types of headers.
I was just trying to give an idea in the first comment but should have probably mentioned that there.

Real code would look more like this:

```typescript
const zipFiles = context.docx.rawZipFile.listFiles();
const headerAndFooterPaths = zipFiles.filter(file => file.startsWith('word/header') || file.startsWith('word/footer'));
```

But again, there might be some corner cases I'm missing here. The complete solution, and most safe thing to do would be to read the header paths from the `document.xml.rels` file (read [here](http://officeopenxml.com/WPSectionHeaderReference.php)). This is part of the reason I haven't added this functionality to the library yet as I want to make sure that when I do it won't throw confusing errors.

**Comment by Neko-Mashiro** [comment]
I see, thank you for clarifying

**Comment by alonrbar** [comment]
Headers and footers support added in v0.12.0

**Comment by JarothD** [comment]
Hey alonrbar, thank for you excellent work. 

I just want to ask how is the proper way to make a simply change just in the header, to replace the variables. 
because you added the support for that, but I can't find how to use it. With the example above is using tags and I think maybe it won't work for me. Any suggestion?

**Comment by JarothD** [comment]
To use this extension with only JS
` class HeaderExtension extends TemplateExtension {
     async execute(data, context) {
        const headerPaths = [ 'word/header1.xml', 'word/header2.xml', 'word/header3.xml' ];
        for (const headerPath of headerPaths) {
            const headerText = await context.docx.rawZipFile.getFile(headerPath).getContentText();
            const headerXml = this.utilities.xmlParser.parse(headerText);
            await this.utilities.compiler.compile(headerXml, data, context);
            const processedHeaderText = this.utilities.xmlParser.serialize(headerXml);
            context.docx.rawZipFile.setFile(headerPath, processedHeaderText);

       }
    }
}` 
Then to add it to your previous workflow just do this:
`const headerExtension = new HeaderExtension();
        const handler = new TemplateHandler({
            extensions: {
                afterCompilation: [
                    headerExtension 
                ]
            }
        });
        const file = fs.readFileSync(filename);
        
        const doc = await handler.process(file, toFill)`
        
        
        Thanks to alonrbar...
