### ISSUE TITLE
Detect tags without replacement option

### ISSUE THREAD

**Issue by Neko-Mashiro** [alonrbar/easy-template-x#31]
Is it possible to detect tags that don't have any corresponding data to be replaced into. 

For example: 

Data:
```
{
  "Beers": [
    { "Brand": "Carlsberg" },
    { "Brand": "Leaf Blonde" },
    { "Brand": "Weihenstephan" }
  ]
}
```

Tags in my template:
`{#Beers}{Brand}_{Price}${/Beers}`

Can I detect that {Price} doesn't have any data and get that tag?

**Comment by alonrbar** [comment]
Yes you can. 
You can use the `TemplateHandler.parseTags` method to get all tags in the template and then compare that against the data provided. You can check [this unit test](https://github.com/alonrbar/easy-template-x/blob/master/test/unit/templateHandler.tests.ts#L11) as a reference.
