### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by Neko-Mashiro** [alonrbar/easy-template-x#32]
I get "An accessor cannot be declared in an ambient context." in multiple files when running npm start.
Is the issue that I am running on a too old version of typescript or something else? 
I am currently running Typescript 2.7.2 and Angular 6.1.

**Comment by alonrbar** [comment]
Can you please be more specific? A file and a line number would be helpful, so does a complete error message.
Also, are you using the latest version of this library?

**Comment by alonrbar** [comment]
Oh, I just realized you've stated 2.7.2 not 3.7.2. Yes, your Typescript is quite old and needs to be updated.
