### ISSUE TITLE
In the future, we should implement a change to the footer.

### ISSUE THREAD

**Issue by cvaize** [alonrbar/easy-template-x#35]
![DeepinScreenshot_20200424225012](https://user-images.githubusercontent.com/26907947/80242011-108e8b80-867e-11ea-964d-fd3b992d9f2a.png)

**Comment by alonrbar** [comment]
Hi,
You are right it should be implemented and will be in the future, although I can't commit as to when it will happen.
In the meanwhile checkout my comment [here](https://github.com/alonrbar/easy-template-x/issues/25#issuecomment-584028096) to see how you can implement it pretty easily using the extensions API.

**Comment by alonrbar** [comment]
Related to #25

**Comment by alonrbar** [comment]
Footer spec overview: http://officeopenxml.com/WPfooters.php

**Comment by cvaize** [comment]
I created a simple extension. The code is very bad, but it works. Only Nodejs, Only `TextPlugin`. https://github.com/cvaize/easy-template-x-extension-footer

**Comment by cvaize** [comment]
The `Link Plugin` exactly handles footer incorrectly in my extension, but the extension solves my problem.

**Comment by alonrbar** [comment]
I looked at your code, looks pretty nice actually 👍 

I see that you had to overwrite some private fields there, I'll try to improve that in the future so that won't be necessary. I'll also check why the link plugin doesn't work in the footer. Hopefully I will get to that next week. 

Do you see any other issues worth noticing when I'll do that?

**Comment by cvaize** [comment]
After generating the link in footer, the error looks like this.
![image](https://user-images.githubusercontent.com/26907947/81964795-8b6d1580-9630-11ea-965c-5566f44412f5.png)

**Comment by cvaize** [comment]
There were no problems with `LoopPlugin`.
![image](https://user-images.githubusercontent.com/26907947/81965339-5b724200-9631-11ea-9019-5d8551ba6c94.png)

**Comment by cvaize** [comment]
My extension also can't insert an image.
![image](https://user-images.githubusercontent.com/26907947/81965931-303c2280-9632-11ea-8166-791e13d67a2c.png)

**Comment by cvaize** [comment]
Thank you for your work!

**Comment by alonrbar** [comment]
Headers and footers support added in v0.12.0

**Comment by cvaize** [comment]
Thanks!
