### ISSUE TITLE
Images in nested arrays

### ISSUE THREAD

**Issue by Ractivuss** [alonrbar/easy-template-x#37]
Hi, it's me again. Now I'm having a new trouble wich is that I have a nested array with images inside and when I print the document it just writes `[object Object]`.

My array looks like this:
`items [
name: 'product 1',
description: 'Description for product 1 here....',
image: {
_type: 'image',
source: <source>
format: 'image/png',
width,
height,
},
name: 'product 2',
description: 'Description for product 2 here....',
image: {
_type: 'image',
source: <source>
format: 'image/png',
width,
height,
},
]`

and my docx document looks like this:
`
{#items}
{name}
{description}
{image}
{/items}
`

It prints the name and description correctly, but for the image prints `[object Object]`

Help!:(

**Comment by alonrbar** [comment]
Hi, is there a chance you forgot to wrap each object with curly braces?
You mentioned `[ name: 'product 1', description: 'Description for product 1 here....', image: { _type: 'image', source: <source> format: 'image/png', width, height, }, ... ]`
But it should be `[ { name: 'product 1', description: 'Description for product 1 here....', image: { _type: 'image', source: <source> format: 'image/png', width, height, } }, ... ]`

**Comment by Ractivuss** [comment]
Mmm... I wrote that wrong, but that's how I have my nested array. Because it reads correctly the other properties 'name', 'description' but the image prints [object Object] wich is correct because is an object.

It's like that images in an nested array doesn't seem to work correctly.

By the way, thanks for your response :) and sorry for my delay in responding :(

**Comment by alonrbar** [comment]
Hi, take your time, no rush here :)

I've checked it now and it does not seem to reproduce.
I've added this test method to the [image.tests.ts](https://github.com/alonrbar/easy-template-x/blob/master/test/fixtures/image.tests.ts) file and manually verified the output and everything looks fine. I think cloning the repo and running this test on your machine can help in finding what's may be wrong.

```typescript
    it("replaces an image tag in nested loops", async () => {

        const handler = new TemplateHandler();

        const template = readFixture("loop - nested with image.docx");
        const imageFile = readResource("panda1.jpg");

        const imageData = {
            _type: 'image',
            format: MimeType.Jpeg,
            source: imageFile,
            height: 325,
            width: 600
        };
        const itemData = {
            loop_prop2: [
                { simple_prop: imageData }
            ]
        };
        const data = {
            loop_prop1: [itemData]
        };
        for (let i = 0; i < 10; i++) {
            data.loop_prop1.push(itemData);
        }

        const doc = await handler.process(template, data);

        // const docXml = await handler.getXml(doc);
        // expect(docXml).toMatchSnapshot();

        writeTempFile('image - nested loop - output.docx', doc);
    });
```

**Comment by Ractivuss** [comment]
It's not working, it still prints [object Object] in the docx ... But one question, where did you require('') that "MimeType"?

**Comment by Ractivuss** [comment]
Sorry!!! My mistake! I was doing something wrong! ... It worked! :)

**Comment by Aira-AY** [comment]
> Sorry!!! My mistake! I was doing something wrong! ... It worked! :)

Sorry to bother, actually i met the same problem. Could you remember how to solve the [object object]？
