### ISSUE TITLE
Base64 image

### ISSUE THREAD

**Issue by Arthemis97** [alonrbar/easy-template-x#40]
Hi,
Can I add a base64 image instead of file?

**Comment by alonrbar** [comment]
Yes, just convert it to binary 😉

### Server side

In Node.js it's super easy:
```javascript
const buf = Buffer.from(base64String, 'base64')
```

### Client side

In client side JS you can convert to **ArrayBuffer** by doing this:
```javascript
function base64ToArrayBuffer(base64String) {
    const binaryString = atob(base64String);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
}
```

or to **Blob** by doing this:
```javascript
const mime = "image/jpeg";
const res = await fetch(`data:${mime};base64,` + base64Data);
const blob = await res.blob();
```

(easy-template-x doesn't care if you use ArrayBuffer or Blob)

#### You can read more and find other answers here:
- https://stackoverflow.com/questions/21797299/convert-base64-string-to-arraybuffer
- https://stackoverflow.com/questions/27980612/converting-base64-to-blob-in-javascript
- https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript

**Comment by CarlosWosiak** [comment]
Hi, I did it in a nodejs app, the buffer was generated successfully, could you please inform me how would I add it to my template with the image plugin?
![image](https://user-images.githubusercontent.com/29006379/106598347-5d20c480-6536-11eb-88d8-876192883015.png)
