### ISSUE TITLE
Keep {tag} if value null

### ISSUE THREAD

**Issue by shaliake** [alonrbar/easy-template-x#45]
It's possible to keep {tag} if the value is null, empty string, etc?  For single value I just replace do replacing like this:
`                orderDate: currentClaim.orderDate ?
                    moment(currentClaim.orderDate).format("DD.MM.YYYY") : "{orderDate}",`

But how do it for arrays?

`{#reviews}{position}			               {submitted} {acceptanceText} {fullName}{/reviews}`

**Comment by aylabbs** [comment]
My guess is no.

If this is something you need, add a variable to your data with an array to check if the reviews array has elements.

```
const data = {
  reviews,
  noReviews: reviews.length ? [] : [{ display: `{#reviews}{position} {submitted} {acceptanceText} {fullName}{/reviews}`}]
}
```
then you can do:

```
{#reviews}{position} {submitted} {acceptanceText} {fullName}{/reviews}
{#noReviews}{display}{/noReviews}
```
I haven't tested this, but I don't see why it wouldn't work.

**Comment by alonrbar** [comment]
As @aylabbs said this is currently not supported and you can use some smart workarounds as suggested.  
If you fancy a "real" solution it should be relatively easy to implement by modifying the [TemplateCompiler.doTagReplacements](https://github.com/alonrbar/easy-template-x/blob/master/src/compilation/templateCompiler.ts#L55) method. I would probably control it by adding a flag to the TemplateCompiler constructor (and at the same opportunity will change its list of arguments into an options object as it is getting quite large).
I may implement this in the future but not for the very near one. If you prefer you are welcome to implement it yourself and PR.  
Hopes that helps.
