### ISSUE TITLE
Not being able to display an array inside if condition

### ISSUE THREAD

**Issue by sahar-fehri** [alonrbar/easy-template-x#49]
Hello everyone, 

I have been trying to display an array inside if condition.
Here is the template I use inside myc docx file: 

```
{#participants}
{#display}
{name}
	{#list}
		Name : {name}
		Surname : {surname}	
	{/list}
{/}
{/ participants }
```

And here is the data I pass to the template:

```
       const data = {
            "participants": [
                {
                    "display": true,
                    "name" : "bob",
                    "list": [
                        { "no": 1, "name": "Bryson", "surname": "Pike" },
                    ]
                },
                {
                    "display": true,
                    "name" : "alice",
                    "list": [
                        { "no": 3, "name": "Charis", "surname": "Hilton" },
                        { "no": 4, "name": "John", "surname": "Plant" },
                    ]
                },
                {
                    "display": false,
                    "name" : "bruno",
                    "list": [
                        { "no": 6, "name": "Beatriz", "surname": "Schmitt" },
                        { "no": 7, "name": "Fionn", "surname": "Lyons" },
                        { "no": 8, "name": "Pedro", "surname": "Compton" }
                    ]
                }
            ]
        }


        const handler = new TemplateHandler();
        const doc = await handler.process(templateFile, data);
```

And here is a screenshot of the output.docx file generated :
![image](https://user-images.githubusercontent.com/10994169/118818429-9a764b80-b8b4-11eb-9498-39e0c99fc1f9.png)

As you can see the name displayed is the name of participants and not the in in the list, also no surname is displayed..

Am I doing something wrong in the template or is this not supported with easy-template-x ?

PS: if I remove the condition {#display} {/} it works fine and displays the right values, so it seems that the problem is doing a loop inside a condition.

Thank you!

**Comment by alonrbar** [comment]
Yes, you are right. Loops inside simple conditions are not well supported out of the box. Have you tried using https://github.com/alonrbar/easy-template-x-angular-expressions ?

**Comment by sahar-fehri** [comment]
@alonrbar Thanks a lot for your reply!
I will try using what you linked, hope it works.
Thnx!

**Comment by HenriqueSerafim13** [comment]
Hey @sahar-fehri  did get this issue resolved?

**Comment by sahar-fehri** [comment]
Hi @HenriqueSerafim13 , no :/ i tried another library
