### ISSUE TITLE
Unable to replace Image in Browser

### ISSUE THREAD

**Issue by rRakarare** [alonrbar/easy-template-x#51]
Hey guys,
i was trying to replace an image in a react-app by following the documentation. Text replacing is working fine but image replacing is just not working.
You can have a look at my [codesandbox](https://codesandbox.io/s/currying-forest-8lcr2?file=/src/App.js). If you remove the image property in the data object its working but when i try to replace with image property, it´s giving me the following error message (Binary type 'Promise' is not supported). So im wondering if there is something wrong with my image format or if there´s another problem. I tried with blob and ArrayBuffer.
Hope you guys can help me here.
Thanks

PS: Since downloading contents at codesandbox is not working anymore i just logged the error.

**Comment by alonrbar** [comment]
Hi, you just missed an `await` in line 51...

**Comment by rRakarare** [comment]
Thanks, i got it working in the updated codesandbox 👍
