### ISSUE TITLE
Tags inside conditions (in a table)

### ISSUE THREAD

**Issue by HenriqueSerafim13** [alonrbar/easy-template-x#52]
Hello again :)

Another question, is it possible to add a simple text tag inside a condition? If yes, what´s the approach?

i want something like this 
![Screenshot 2021-05-21 at 13 04 10](https://user-images.githubusercontent.com/84539121/119134901-9faed400-ba35-11eb-92a7-07868f2d46f4.png)

and i´ve tried using the #lines example and the other tags outside.. 
![Screenshot 2021-05-21 at 13 10 01](https://user-images.githubusercontent.com/84539121/119135138-ec92aa80-ba35-11eb-8cd0-baf9819b2ddd.png)
i get Node has no Parent Error

next i tried this
![Screenshot 2021-05-21 at 13 12 36](https://user-images.githubusercontent.com/84539121/119146277-60d34b00-ba42-11eb-91d6-f7c4addb47d9.png)
and this
![Screenshot 2021-05-21 at 13 31 27](https://user-images.githubusercontent.com/84539121/119146284-62047800-ba42-11eb-805a-8fe70de0ffe3.png)

same error.. any hint on how to achieve this?

**Comment by HenriqueSerafim13** [comment]
found another way around.. since the {DataAssuntoEncerrado} wont be visible if dont have data just have the {#Invisible} around "Data Encerramento" and it worked..

**Comment by alonrbar** [comment]
The conditions issue is now solved with the new v3.0.0 (and [this commit](https://github.com/alonrbar/easy-template-x/tree/d588e0c5e76a5bb1abc90fdb23c19844cd64db6b) in particular) but unfortunately to completely fix this issue and make things works inside a table, further work is required. This will be solved when issue #50 is solved.

**Comment by alonrbar** [comment]
Fixed in v4.0.0
