### ISSUE TITLE
Get data structure/tree from docx template

### ISSUE THREAD

**Issue by ChristopherCapito** [alonrbar/easy-template-x#55]
Greetings!

First of all, thank you very much for all the work you put in thus far. I really like the concept and I think it can be greatly expanded upon. For my current use case, I need to read the docx template, and then extract the tags, but in a hierarchical order.

Could you point me in the right direction in terms of how to achieve this? I tried digging into the libraries depths but was a little overwhelmed by the complexity since I have no experience working with XML.

As an example though, say we have the following tags in a template (which I know I can get from parseTags)

```
{color}
{#master}
{author}
{#nest_1_cond}
{copyright}
{/}
{#nest_2_cond}
{someVar}
{/}
(/)
(subject)
```

this should result in the following object
```
{
  color: "",
  master: {
    author: "",
    nest_1_cond: {
      copyright: "",
    },
    nest_1_cond: {
      someVar: "",
    },
  },
 subject:""
}
```

I know there are some problems with this right of the bat. For example, 
1. how do I distinguish between a table-loop, and a simple condition loop? 
2. Also, I noticed I can not place two conditionals in a row without wrapping them inside another condition, like the above nest_1_cond and nest_2_cond which are wrapped inside the master.

I am half sure that this functionality is already there, at least in reverse since you somehow need to find all the tags and all the loops for the loop functionality. But I am unsure on how to reverse construct an object from that, if that is even practicable. If you have any suggestions, ideas or further reading - I 'll gladly take it

**Comment by ChristopherCapito** [comment]
Okay I think I got it actually. Just some simple object manipulation. However I found that it is not possible to have an object nested in an object, is that a correct assessment?

**Comment by alonrbar** [comment]
Hi, if you already know you can achieve use `parseTags` then the missing piece is to iterate on the result and build the tree. Something like this should work:
```typescript
import { TagDisposition } from 'easy-template-x'

const tree = {}; // this will hold the resulting tree

// we use this array as a stack to keep track of parent-child relations 
// (we could have instead store a pointer on each child to it's parent, 
// say on a "_parent" field)
const parents = []; 

const tags = await templateHandler.parseTags(template);
let node = tree;
foreach (const tag of tags) {
 
  if (tag.disposition === TagDisposition.Open) {
    node[tag.name] = {};
    parents.push(node);
    node = node[tag.name];
  }

  if (tag.disposition === TagDisposition.Close) {
    if (parents.length === 0) {
      throw new Error(`Invalid tag structure, tag "${tag.rawText}" is closed before it was open`)
    }
    node = parents.pop();
  }

  if (tag.disposition === TagDisposition.SelfClosed) {
    node[tag.name] = "";
  }
}
```

**Comment by alonrbar** [comment]
Hi again,

About your second point, this should not be necessary. 
I'm closing this issue because the main question mentioned in the issue title should be resolved by my previous comment.

If the second point still causes you problems please open another issue for it.
If you do, it would be helpful to know some details about your template in that regard, specifically whether you do that inside a table or not.

**Comment by ChristopherCapito** [comment]
Hello there, I was on vacation and other work flooded me. Thanks for the answer! As for the other issue, yes it is still causing a problem, and in due time I will create a new ticket. Thanks for the help!
