### ISSUE TITLE
How to add content controls with text in them.

### ISSUE THREAD

**Issue by sebastianrogers** [alonrbar/easy-template-x#6]
Excellent library but unfortunately I need to generate forms complete with filled in content controls.

Any idea how this could be done?

**Comment by alonrbar** [comment]
Thanks :)

To be honest, up until now I was not aware that content controls even exists 😅 
I've looked a bit at how they are implemented and it seems like quite heavy stuff. I feel that this is a bit out of scope for me at the moment, sorry.

You are of course more than welcome to implement the necessary [plugin](https://github.com/alonrbar/easy-template-x/tree/develop/src/plugins) and pull-request it to the repo :)
From a short search I did the best source for their xml structure I could find was [this](http://www.datypic.com/sc/ooxml/e-w_sdtContent-2.html), and also [this](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#getooxml--) may be an interesting option to explore.
A basic research will probably best start with just creating a simple document with a single control and unzipping it.

Again, sorry I could not be of more help.

**Comment by alonrbar** [comment]
Thinking about it a little more, maybe you can just use tags inside the content controls, have you tried something like it?

**Comment by sebastianrogers** [comment]
I tried it and they are just ignored, plus there are odd ones like check boxes you can't type in.

The first link is the way to go, the second is for an Office Add In.

Let me clear my decks here and I'll start in on a plug in for it.

Cheers

Sebastian

**Comment by sebastianrogers** [comment]
Hi There

Right started work on a plug in and it won't work because the delimiterParser won't pick up the SDT nodes even if wrapped in {}.

I had some success with using the rawXml plugin but this causes an issue where another entity has issued the template, e.g. official form, and it has to be returned with identical internal formatting.

Instead it needs a 'nodeParser' in the compiler that can pick up specific nodes, e.g. w:sdt, rather than {} enclosed strings.  Then produce a list of such nodes with identifiers based on the w:sdtPr/w:id which can be combined with a data structure to replace the innerXml of the w:sdtContent node.

It seems there are two ways to proceed:

1. Add this code to your excellent project so it handles both cases, probably with a tag Plugin extension module so other inherent tags can be handled this way.
2. Take your code as a great starting point and produce a new project that just handles node replacement.

What is your feeling on how to proceed @alonrbar ?

Raring to go.

Sebastian

**Comment by alonrbar** [comment]
Hi,

Assuming I understand correctly, what comes to my mind is another form of extensibility option.
What do you think about the following `Extension`:

```typescript
interface ITemplateExtension {
   execute(utilities: PluginUtilities, context: TemplateContext): void | Promise<void>;
}
```

These "extensions" will have several injection point, say "before-parse", "after-parse", "before-save".
They will be specified either as an additional `TemplateHandlerOption` or as an optional argument to the `process` method.

Then you could write something like this to implement your desired logic:

```typescript
class ContentControlsFormExtension implements ITemplateExtension {

   public async execute(utilities: PluginUtilities, context: TemplateContext) {
      const documentRoot = await context.docx.getDocument();
      // 1. traverse nodes and find all SDT nodes using 'findNextNode'
      // 2. your custom logic...
   }

   private findNextNode(node: XmlNode, depth: XmlDepthTracker): XmlNode {
       // export logic from DelimiterSearcher (thinking: Dfs.findNextNode)
   }
}
```

I think this opens some interesting new possibilities such as a `MetadataExtension` that will set document author, `HighlightExtension` that will highlight certain sentences and so on.

What do you think?

**Comment by sebastianrogers** [comment]
I like it.  Gives great flexibility to handle 'invisible' sections of the document.

However does it need extension points or should it just be an array of ITemplateExtensions with the default being just the existing code as an extension then everything is equal.

Something like

public extensions?: TemplateExtensions[] = createDefaultExtensions();

Which then just get called in order.

**Comment by alonrbar** [comment]
Interesting point... I'll take that into account and work on the final api the next couple of days. Will keep you posted for feedback.

Meanwhile, I think you can start implementing based on the this initial draft if you wish. I believe it won't change dramatically, meaning, you'll have the TemplateContext and the utilities available to you to work with one way or another.

**Comment by sebastianrogers** [comment]
Yes I can.  I'll get cracking.

**Comment by sebastianrogers** [comment]
Been working on using the template idea above but realised it ends up duplicating a lot of the compiler you've already written.

What about allowing multiple parsers instead?

`public parsers?: Parsers[] = createDefaultParsers();`

That way it can keep the compile structure they just have to return a Tag[] which is appended to the list of tags.

Then it can use a plugin to do the replace?

**Comment by sebastianrogers** [comment]
I have a basic version working based on templates, does plain and rich text content controls only.

Now I am even more familiar with the code I'd like to try adding an array of Searchers rather than Parsers as an experiment and then using plug ins to write the resulting tags out.  This seems a very lightweight integration indeed.

**Comment by alonrbar** [comment]
Can you share some code examples? 
It will be easier for me to get exactly what you mean and possibly help and provide some meaningful input. A commit to your fork (in whatever branch you wish) will be a good place to do that.

**Comment by sebastianrogers** [comment]
I've committed a version here based on the extension idea: https://github.com/sebastianrogers/easy-template-x.

I'll do a branch based on multiple parsers on Monday and commit it, my attempt just to replace the searcher didn't work as it needs a custom tag builder as well.

**Comment by alonrbar** [comment]
The current version seems pretty good.
I'm not quite sure why another approach is needed but will wait patiently till Monday ;) 
In the meanwhile, if I may comment, the SDT tags replacement does not necessarily falls into the tags and plugins category, don't force yourself into it if it causes you troubles. The extension you wrote can have it's own modular structure internally which is independent of that (see for example what I've done with the [LoopPlugin](https://github.com/alonrbar/easy-template-x/blob/master/src/plugins/loopPlugin.ts)).

**Comment by sebastianrogers** [comment]
Yes you are right, although the tags look like they will work for plain nodes they are not actually a good match.  I thought that by just adding more tags via a separate parser I would be able to leverage all of the code you have written, but the logic is too specific, and more complex than simple node detection requires.  Similarly the plugin module makes assumptions that are not correct for a simple node replacement model.

However I needed to work through it myself to be sure.

I'm working on porting my changes back into the extensions version above but with a plugin facility based on yours.

I have a tight deadline on this so hopefully there will be something to look at tomorrow morning.

**Comment by sebastianrogers** [comment]
Just keeping you in the loop I'll have a pull request ready later this week.

1. Uses the extension idea you suggested, essentially what you have seen up until now.
2. Extends the plugin mechanism to work with extensions, to prevent there being two almost identical ones.
3. Handles data binding as well as content controls, I need this for the word 'forms' that we need to produce, an unexpected 'bonus' and not something anyone else seems to have.

Cheers

Sebastian

**Comment by alonrbar** [comment]
Hi, 
Glad to hear. Will take a look as soon as you PR.

**Comment by sebastianrogers** [comment]
Sorry for the delay, busy with other work.

I have a version ready to go that has a generic extension mechanism with two extensions:

- Content Control, for updating content controls (fields) based on their IDs.
- Data Binding, for updating bound data and hence any content control bound to them.

I'll sort out a Pull Request for them.

**Comment by sebastianrogers** [comment]
Just one issue in that the code doesn't match up now.

Which branch should I make the pull request to?

Extensions?

**Comment by alonrbar** [comment]
Hi,
Interested in seeing your solution.
Please make the PR to the Extensions branch.

**Comment by sebastianrogers** [comment]
Just having some issues with the CI failing type checks...

**Comment by alonrbar** [comment]
Version 0.9.0 published :)

**Comment by alonrbar** [comment]
@sebastianrogers does #28 closes this issue?

**Comment by sebastianrogers** [comment]
Absolutely.

Its been a pleasure working with you on this.  I've learnt a lot and enjoyed learning it.

When I have time I'll do a content control extension.

Cheers

Sebastian

**Comment by alonrbar** [comment]
Same here, thanks a lot for the contribution. It's been a pleasure!
