### ISSUE TITLE
Question: List of tags in document before calling handler.process

### ISSUE THREAD

**Issue by bitfabrikken** [alonrbar/easy-template-x#65]
I find that it would be nice to get a list of actual tags that exist in the document.
This way I know which tags to generate data for - in some cases it can save quite a lot of time.
Is this possible?

**Comment by alonrbar** [comment]
This is possible with `TemplateHandler.parseTags`. Perhaps I should document it in the readme...

**Comment by bitfabrikken** [comment]
That would be wonderful, I think it's pretty common once a project gets to a certain size :)
