### ISSUE TITLE
File crash with hyperlink and hashtag

### ISSUE THREAD

**Issue by Lopez10** [alonrbar/easy-template-x#68]
First of all congratulations for this library.

After testing your library I discovered a **bug**. When you put a hyperlink with a hashtag, the file crashes.

[Corrupto.docx](https://github.com/alonrbar/easy-template-x/files/9470589/Corrupto.docx)
This file doesn't work, because it has a hashtag in the hyperlink.

[Funciona.docx](https://github.com/alonrbar/easy-template-x/files/9470592/Funciona.docx)
But this file works because it doesn´t have a hashtag in the hyperlink.

Could you check it? thanks 😊

**Comment by alon-ananchik** [comment]
I've just checked. Both files load correctly on my machine. I've also checked the internal structure and could not find any issue. Can you re-check your files please?
