### ISSUE TITLE
Is it possible to run easy-template-x purely from html page with js?

### ISSUE THREAD

**Issue by mediabug51** [alonrbar/easy-template-x#70]
Is it possible to run it off a CDN ?
eg: 	<script src="https://cdn.jsdelivr.net/npm/easy-template-x@3.0.2/dist/cjs/easy-template-x.min.js"></script>

Then under HTML <SCRIPT>
import { TemplateHandler } from 'easy-template-x';

I tried the above but fail on the import line

Any kind soul can give me some pointers pls? Thank u in advance.

**Comment by alonrbar** [comment]
Hi,
Short answer - no, it's not possible. Please see my comment [here](https://github.com/alonrbar/easy-template-x/issues/57#issuecomment-885431854) about this.
Longer answer - well, maybe... I haven't tried it myself but these days it should be possible to import ES modules in the browser. You can check these sources here and if you find anything that works for you I'd be happy to hear :)

- https://www.sitepoint.com/using-es-modules/
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by alonrbar** [comment]
Related: #47, #57, #61
