### ISSUE TITLE
getting error Error: Malformed file

### ISSUE THREAD

**Issue by cristtiah** [alonrbar/easy-template-x#71]
I am trying to implement this 

https://codesandbox.io/s/easy-template-x-demo-x4ppu?fontsize=14&module=/index.ts&file=/index.ts:33-48

but I am getting an error from the template.docx - Error: Malformed file detected. make sure the file is a valid docx file

**Comment by alonrbar** [comment]
Just tried to use the live demo and had no issue. What file did you use for the template?
