### ISSUE TITLE
Is it possible to negate a conditition (i.e. {#!valueChecked})?

### ISSUE THREAD

**Issue by caponet** [alonrbar/easy-template-x#75]
Hello,
I can't figure out how negate a condition. I tried this:
```
{#!value}
{#value == false}
{#value != true}
```
But it doesn't work. 
An If/else block style would be great too.
Can you help me?

Thank you

**Comment by alonrbar** [comment]
Hi, by default negation is not supported, but you can check out [this](https://github.com/alonrbar/easy-template-x#advanced-syntax-and-custom-resolvers)  advanced syntax which may provide what you are looking for.

**Comment by caponet** [comment]
Thank You!
