### ISSUE TITLE
The generated docx file don't remove lines if the text is not supposed to be shown

### ISSUE THREAD

**Issue by srz09** [alonrbar/easy-template-x#76]
Hello 👋 

Here is the docx template content I'm using

<img width="792" alt="template" src="https://user-images.githubusercontent.com/6841511/203988663-87c96826-776f-443b-98a8-7290622d67b4.png">

and here is the generated one.

<img width="469" alt="generated" src="https://user-images.githubusercontent.com/6841511/203988658-3b68edf4-5503-47be-a38e-4d43081f8779.png">

As you can see there is a lot of empty space where the table was expected to be rendered (if the condition was true).

I was thinking that setting the condition to false would have automatically remove all the empty lines.

Is there a way to remove those empty lines ?

Thanks a lot and well done for this lib 👍

**Comment by alonrbar** [comment]
Hi, looks like you just need to adjust the position of your condition tags. Instead of doing this:
```
Hello

{# condition}
Table
{/condition}

Rest of the text
```

Consider the following:
```
Hello
{# condition}
Table
{/condition}
Rest of the text
```
You can even go for this:
```
Hello
{# condition}
Table
{/condition}Rest of the text
```
Try to play with it a little until you find what's working for you exactly (I sometimes also play with the line height for fine tuning).
