### ISSUE TITLE
Removal of whitespace from my data

### ISSUE THREAD

**Issue by Moaaz-Hajat** [alonrbar/easy-template-x#79]
I am having a problem removing whitespace from my data. Please find attached a sample of my source code

{HasValue}
{Value}
{Number1}
{Number2}
{Number3}
{Value}
{HasValue}

If {HasValue} returns true the values should be displayed and if {HasValue} returns false the object should be hidden. The problem arises when {HasValue} returns false. The object is hidden from the page but the space allocated for {Value} remains there. Is there a way to remove the space allocated to that object on the page?

**Comment by alonrbar** [comment]
Please take a look at #76, it should have the information you need.
