### ISSUE TITLE
How to add hyper link

### ISSUE THREAD

**Issue by wahabshah** [alonrbar/easy-template-x#8]
I have a question as to how can one add a hyperlink?

Like it is done in this project docx-templates :- [Links](https://www.npmjs.com/package/docx-templates#link)

**Comment by alonrbar** [comment]
Well, now you can :)
Version 0.7.0 was just released and includes a [Link plugin](https://github.com/alonrbar/easy-template-x#link-plugin).

**Comment by alonrbar** [comment]
Actually, I think it may not be properly completed and may not work in all cases. I'll do some finishing tomorrow and publish a new version.

**Comment by wahabshah** [comment]
Thats great to have it enhanced with this feature..
Yeah i mean would it be possible to have it used in the Table rows as well?

**Comment by alonrbar** [comment]
Version 0.7.1 which fixes the plugin was just released and you can start using it.
Yes, you can use the link plugin inside or outside tables with no problem.
