### ISSUE TITLE
Slow performance on several page documents

### ISSUE THREAD

**Issue by whekin** [alonrbar/easy-template-x#80]
I have a document around 10 pages and it has just a couple of tags in the beginning. Generating it on M1 Pro chip takes me more than 20 seconds (handler.process() takes 99% of that time). On AWS t3 micro it takes more than a minute

**Comment by alonrbar** [comment]
Can you share your template?

**Comment by whekin** [comment]
[test-template.docx](https://github.com/alonrbar/easy-template-x/files/10844613/test-template.docx)
Of course. Here I have some tags in the begging and then just a peace of a document. I noticed that when I cut a half of tags it also cuts generation time close to half. Removing a half of that document (not touching tags) also quite shrinks time for generation

**Comment by whekin** [comment]
@alonrbar I've found the issue. It was in my custom scopeDataResolver. The performance of the library is good enough. I'm sorry for disturbing you

**Comment by alonrbar** [comment]
Hi, no problem and thank you for the update.
