### ISSUE TITLE
Auto-max images option

### ISSUE THREAD

**Issue by PaulMcGuinness** [alonrbar/easy-template-x#83]
Hi, I was wondering if I could make a feature request (unless you can think of a quick-fix to do this inline)

Where "autoMax" would set the image to fix either width, height or leave alone by default.

I'm writing some code where it generates network graphs in real-time, and the size of the image can vary from 200x200 to 5000x5000 pixels.

For images, an optional sizing parm:-

{
      _type: "image",
      source: await fs.readFile(value),
      format: "image/png",
      width: z[0],
      height: z[1],
      autoMax: <value>
}

**Comment by alonrbar** [comment]
Closing for now. Feel free to reopen with the following details:
What is the size of the original image, what is the json input and what do you expect as output.
