### ISSUE TITLE
Unable to replace placeholders when library is called in a for loop

### ISSUE THREAD

**Issue by realrecordzLab** [alonrbar/easy-template-x#89]
I'm trying to generate multiple documents using a for loop that will call a method that I've created inside my vue app. Ive noticed that only one placeholder is replaced, the other I have into the document will be replaced with a clank line. Is there any way to fix this or is a bug of the library?

**Comment by alonrbar** [comment]
Closing as obsolete. If this is somehow still relevant, please provide more info about your issue.
