### ISSUE TITLE
Conditional display of data in the template.

### ISSUE THREAD

**Issue by vasumur** [alonrbar/easy-template-x#94]
Thanks for making this library which is helpful to put in a nice looking word document with minimum docx library handling.

Is it possible to show or remove section of a paragraph (or) table etc based on the input flag passed in as data?

We have a need where the users would like to show a section say Audience which has text, tables etc, but only based on the input value.

Regards... Muralee

**Comment by alonrbar** [comment]
Does this do what you need?
https://github.com/alonrbar/easy-template-x#conditions

**Comment by alonrbar** [comment]
That's exactly what this capability does. You don't have to it inside a loop, that was just an example. You can write something like this:
```
{#show logistics}
Logistics
Date: {date}
...
{/show logistics}
```
And have your data loon like this:
```
{
 "show logistics": true,
 "date": ...
}
```

**Comment by vasumur** [comment]
Hi @alonrbar 

I tried 

{
 "show_logistics": true,
  "date": "MyDate"
}

With a template file having the below contents.

{#show_logistics}
Logistics
Date: {date}
{/show_logistics}


And using your demo code sandbox version
https://codesandbox.io/s/easy-template-x-demo-x4ppu?fontsize=14&module=%2Findex.ts

It doesn't seem to work. Can you please take a look at your convenience?

Thanks

**Comment by alonrbar** [comment]
Please note that the live demo uses an older version of the library. You should update the version in your fork of the demo to work with conditions.
