### ISSUE TITLE
Loop with RTL key

### ISSUE THREAD

**Issue by AmitGit217** [alonrbar/easy-template-x#95]
I'm trying to loop in this object:

![Screenshot 2023-07-20 093701](https://github.com/alonrbar/easy-template-x/assets/96522800/f99edbd7-a132-4938-8131-83692d3fa7f0)

With this table:

![Screenshot 2023-07-20 093734](https://github.com/alonrbar/easy-template-x/assets/96522800/7a594d04-4b38-4214-945b-0a2c107c0759)

But the table remains empty.
I successfully did it in English but in Hebrew, it does not work

**Comment by alonrbar** [comment]
Since Hebrew is right-to-left so is the document order and everything else. You need to place the opening tag in the right cell of the row and the closing tag in the left cell. Also, the tag text should begin with the "control characters", i.e. have them on the right, like this `{פרטי_רישוי#}`

**Comment by alonrbar** [comment]
You can see one such example in on of the test templates: https://github.com/alonrbar/easy-template-x/blob/master/test/fixtures/files/real%20life%20-%20he.docx

**Comment by AmitGit217** [comment]
Thank you, Alon. 
We successfully managed to use Hebrew as keys.

**Comment by AmitGit217** [comment]
Thank you, Alon. 
We successfully managed to use Hebrew as keys.
