### ISSUE TITLE
Question: is there a way to use this for text files?

### ISSUE THREAD

**Issue by david-randoll** [alonrbar/easy-template-x#97]
I want to possess a text file containing tags that require substitution with corresponding data. Can I use this library to input a text file and populate it with the necessary data?

**Comment by alonrbar** [comment]
Hi, no, manipulating text files is not supported. This package manipulates Word files, which are basically zipped xml files. The entire templating engine is built around manipulating xml files in a strong-typed manner, something that is significantly different than dimple text files manipulation.
