### ISSUE TITLE
Question: Can I use an http link with image plugin?

### ISSUE THREAD

**Issue by david-randoll** [alonrbar/easy-template-x#98]
I am using the demo site and I am trying to insert an image into the document. I am using the below error: Binary type String is not supported. Does the image plugin support a link as the source? Or how do I make it work? Many thanks!

Data:
![image](https://github.com/alonrbar/easy-template-x/assets/51640895/69b5a84b-1101-4690-bf37-7959f80c7f4b)

Template
![image](https://github.com/alonrbar/easy-template-x/assets/51640895/38082aea-eeff-4b91-9436-772b7f3a9e98)

**Comment by alonrbar** [comment]
You can't use URLs directly in the demo but you can easily achieve what you want by adding some code and doing something like this:
```javascript
const res = await fetch("http://something.com/myimage.png");
const blob = await res.blob();

const data = {
  _type: "image",
  source: blob,
  format: MimeType.Png,
  width: 200,
  height: 200
};
```
